# Generated by Django 4.2.2 on 2023-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
            ],
        ),
    ]
