# Generated by Django 4.2.2 on 2023-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tag',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
    ]
