# Generated by Django 4.2.2 on 2023-07-11 13:07

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.image_upload_path),
        ),
    ]
